import React from 'react';
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '../context/AuthContext'; // Import AuthProvider correctly
import Navbar from "../components/navbar/Navbar";
import Footer from '../components/footer/Footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Custom App component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Include any head metadata here */}
      </head>
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
